# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "hashicorp/precise64"
  config.vm.network :forwarded_port, guest: 9001, host: 9191
  config.vm.provision :shell, path: "bootstrap.sh"
  
  config.vbguest.auto_update = false

  #config.vm.network "private_network", ip: "192.168.33.10"
end
